profile = "codegen"
changelog-seen = 2

[target.'x86_64-unknown-linux-gnu']
llvm-config = "/home/atharv/capstone-llvm/build/bin/llvm-config"

[target.riscv64gc-unknown-none-purecap]
llvm-config = "/home/atharv/capstone-llvm/build/bin/llvm-config"
cc = "/home/atharv/capstone-llvm/build/bin/clang"
ar = "ar"

[llvm]
# download-ci-llvm = false
# optimize = false
link-shared = true
# link-jobs = 8
# targets = "X86;RISCV;AArch64"
# experimental-targets = ""
# clang = true
# build-config = { "LLVM_ENABLE_PROJECTS"="clang;lld" }
# llvm-config = { }

[rust]
optimize = false
debug = true
debuginfo-level = 2
new-symbol-mangling = false
codegen-tests = false
use-lld = true